/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OpenaiAssistantSchema {
  created_at: number;
  description: string;
  id: string;
  instructions: string;
  /**
   * Unknown metadata
   */
  metadata: {
    [k: string]: any;
  };
  model: string;
  name: string;
  object: string;
  response_format?:
    | string
    | {
        type?: string;
        [k: string]: any;
      };
  temperature?: number;
  /**
   * tools resources
   */
  tool_resources?: {
    [k: string]: any;
  };
  /**
   * @minItems 0
   */
  tools: any[];
  top_p?: number;
  [k: string]: any;
}
